src/Entity/Plant.php
<?php

namespace App\Entity;

use App\Repository\PlantRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PlantRepository::class)]
class Plant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;


    #[ORM\Column]
    #[Assert\PositiveOrZero]
    private ?int $minNumberOfDaysToWater = 2;

    #[ORM\Column]
    #[Assert\PositiveOrZero]
    #[Assert\GreaterThanOrEqual(propertyPath: "minNumberOfDaysToWater", message: "The value should be greater than min number of days to water or equal")]
    private ?int $maxNumberOfDaysToWater = 20;

    #[ORM\Column(type: Types::SIMPLE_ARRAY, nullable: true)]
    private ?array $fertilizers = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $lastWateringDate = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt;

    #[ORM\Column(nullable: true)]
    #[Assert\PositiveOrZero]
    #[Assert\LessThan(20000)]
    private ?int $height = null;

    #[ORM\Column]
    #[Assert\PositiveOrZero]
    private ?int $volumeOfWaterInMLperCMofHeight = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getMinNumberOfDaysToWater(): ?int
    {
        return $this->minNumberOfDaysToWater;
    }

    public function setMinNumberOfDaysToWater(int $minNumberOfDaysToWater): static
    {
        $this->minNumberOfDaysToWater = $minNumberOfDaysToWater;

        return $this;
    }

    public function getMaxNumberOfDaysToWater(): ?int
    {
        return $this->maxNumberOfDaysToWater;
    }


    public function setMaxNumberOfDaysToWater(int $maxNumberOfDaysToWater): static
    {
        $this->maxNumberOfDaysToWater = $maxNumberOfDaysToWater;

        return $this;
    }

    public function getFertilizers(): ?array
    {
        return $this->fertilizers;
    }

    public function setFertilizers(?array $fertilizers): static
    {
        $this->fertilizers = $fertilizers;

        return $this;
    }

    public function getLastWateringDate(): ?\DateTime
    {
        return $this->lastWateringDate;
    }

    public function setLastWateringDate(?\DateTime $lastWateringDate): static
    {
        $this->lastWateringDate = $lastWateringDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(?int $height): static
    {
        $this->height = $height;

        return $this;
    }

    public function getMaxDaysTillNextWatering(): int
    {
        $today = new \DateTime();
        $last = $this->lastWateringDate ?? $this->createdAt;

        $maxNext = (clone $last)->modify('+' . $this->getMaxNumberOfDaysToWater() . ' days');
        if ($maxNext < $today) {
            return 0;
        }

        $maxDiff = $today->diff($maxNext)->days;
        return (int) $maxDiff;

    }

    public function getNextWatering(): string
    {
        $today = new \DateTime();
        $last = $this->lastWateringDate ?? $this->createdAt;

        $minNext = (clone $last)->modify('+' . $this->getMinNumberOfDaysToWater() . ' days');
        $maxNext = (clone $last)->modify('+' . $this->getMaxNumberOfDaysToWater() . ' days');

        $minDiff = max(0, $today->diff($minNext)->days);
        $maxDiff = $today->diff($maxNext)->days;

        if ($minDiff == $maxDiff) {
            return "$minDiff";
        }

        return "$minDiff - $maxDiff";
    }

    public function getVolumeOfWaterInMLperCMofHeight(): ?int
    {
        return $this->volumeOfWaterInMLperCMofHeight;
    }

    public function setVolumeOfWaterInMLperCMofHeight(int $volumeOfWaterInMLperCMofHeight): static
    {
        $this->volumeOfWaterInMLperCMofHeight = $volumeOfWaterInMLperCMofHeight;

        return $this;
    }

    public function getVolumeOfWaterInML(): ?int
    {
        return ($this->getVolumeOfWaterInMLperCMofHeight()) * ($this->getHeight());
    }

}

src/Form/PlantType.php
<?php

namespace App\Form;

use App\Entity\Plant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('minNumberOfDaysToWater')
            ->add('maxNumberOfDaysToWater')
            ->add('fertilizers', ChoiceType::class, [
                'choices' => [
                    'NPK' => 'NPK',
                    'Compost' => 'Compost',
                    'Manure' => 'Manure',
                    'Organic mix' => 'Organic mix',
                    'Biohumus' => 'Biohumus',
                    'Bone meal' => 'Bone meal',
                    'Fish emulsion' => 'Fish emulsion',
                    'Seaweed (Kelp)' => 'Seaweed (Kelp)',
                    'Superphosphate' => 'Superphosphate',
                    'Potassium sulfate' => 'Potassium sulfate',
                ],
                'multiple' => true,
                'expanded' => false,
            ])
            ->add('height')
            ->add('volumeOfWaterInMLperCMofHeight', TextType::class, ['label' => 'Volume of water in ml per cm of height'])
            ->add('lastWateringDate');

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Plant::class,
        ]);
    }
}

src/Controller/PlantController.php
<?php

namespace App\Controller;

use App\Entity\Plant;
use App\Form\PlantType;
use App\Repository\PlantRepository;
use DateTime;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/plant')]
final class PlantController extends AbstractController
{
    #[Route(name: 'app_plant_index', methods: ['GET'])]
    public function index(PlantRepository $plantRepository, Request $request, EntityManagerInterface $em): Response
    {
        $page = $request->query->getInt('page', 1);

        $plants = $em->createQueryBuilder()
            ->select('plants')
            ->from(Plant::class, 'plants')
            ->setFirstResult(10 * $page - 10)
            ->setMaxResults(10)
            ->getQuery()
            ->getResult();

        return $this->render('plant/index.html.twig', [
            'plants' => $plants,
            'page' => $page
        ]);
    }

    #[Route('/new', name: 'app_plant_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $plant = new Plant();
        $form = $this->createForm(PlantType::class, $plant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $plant->setCreatedAt(new DateTimeImmutable());
            $entityManager->persist($plant);
            $entityManager->flush();



            return $this->redirectToRoute('app_plant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('plant/new.html.twig', [
            'plant' => $plant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_plant_show', methods: ['GET'])]
    public function show(Plant $plant): Response
    {
        return $this->render('plant/show.html.twig', [
            'plant' => $plant,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_plant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Plant $plant, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlantType::class, $plant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_plant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('plant/edit.html.twig', [
            'plant' => $plant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_plant_delete', methods: ['POST'])]
    public function delete(Request $request, Plant $plant, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $plant->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($plant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_plant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/plant/_delete_form.html.twig
<form method="post" action="{{ path('app_plant_delete', { id: plant.id }) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ plant.id) }}" />
  <button class="btn btn-danger ms-4">Delete</button>
</form>

templates/plant/_form.html.twig
{{ form_start(form, { 'data-turbo': 'false' }) }}
{{ form_widget(form) }}
<button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/plant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Edit Plant
{% endblock %}

{% block body %}
  <h1>Edit Plant</h1>

  {{ include('plant/_form.html.twig', { button_label: 'Update' }) }}

  <a href="{{ path('app_plant_index') }}" class="btn btn-primary">back to list</a>

  {{ include('plant/_delete_form.html.twig') }}
{% endblock %}

templates/plant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Plant index
{% endblock %}

{% block body %}
  <div class="container m-auto">
    <table class="table table-hover" style>
      <thead>
        <tr>
          <th>Name</th>
          <th>Days till next watering (min-max)</th>
          <th>Water volume (ml)</th>
          <th>Last watering date</th>
          <th>Description</th>
          <th>Fertilizers</th>
          <th>Height (cm)</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for plant in plants %}
          <tr style="background: {{ plant.getMaxDaysTillNextWatering == 0 ? 'red' : plant.getMaxDaysTillNextWatering <= 2 ? 'orange' : 'green' }};">
            <td style="background-color: rgba(255, 255, 255, 0.5)">{{ plant.name }}</td>
            <td style="background-color: rgba(255, 255, 255, 0.5)">{{ plant.getNextWatering }}</td>
            <td style="background-color: rgba(255, 255, 255, 0.5)">{{ plant.getVolumeOfWaterInML }}</td>
            <td style="background-color: rgba(255, 255, 255, 0.5)">{{ plant.lastWateringDate|date('d.m.Y') }}</td>
            <td style="background-color: rgba(255, 255, 255, 0.5)">{{ plant.description }}</td>
            <td style="background-color: rgba(255, 255, 255, 0.5)">{{ plant.fertilizers|join(', ') }}</td>
            <td style="background-color: rgba(255, 255, 255, 0.5)">{{ plant.height }}</td>
            <td style="background-color: rgba(255, 255, 255, 0.5)">
              <a href="{{ path('app_plant_show', { id: plant.id }) }}" class="btn btn-primary btn-sm">show</a>
              <a href="{{ path('app_plant_edit', { id: plant.id }) }}" class="btn btn-primary btn-sm">edit</a>
            </td>
          </tr>
        {% else %}
          <tr>
            <td colspan="7">no records found</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  {% if page > 1 %}
    <a href="{{ path('app_plant_index', { page: page - 1 }) }}" class="btn btn-primary ms-4">prev</a>
  {% endif %}
  {% if plants %}
    <a href="{{ path('app_plant_index', { page: page + 1 }) }}" class="btn btn-primary ms-4">next</a>
  {% endif %}

  <a href="{{ path('app_plant_new') }}" class="btn btn-primary ms-4">Create new</a>
{% endblock %}

templates/plant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  New Plant
{% endblock %}

{% block body %}
  <h1>Create new Plant</h1>

  {{ include('plant/_form.html.twig') }}

  <a href="{{ path('app_plant_index') }}" class="btn btn-success">back to list</a>
{% endblock %}

templates/plant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Plant
{% endblock %}

{% block body %}
  <div class="container">
    <h1>Plant</h1>
    <table class="table">
      <tbody>
        <tr>
          <th>Id</th>
          <td>{{ plant.id }}</td>
        </tr>
        <tr>
          <th>Name</th>
          <td>{{ plant.name }}</td>
        </tr>
        <tr>
          <th>Days till next watering</th>
          <td>{{ plant.getNextWatering }}</td>
        </tr>
        <tr>
          <th>Volume of water in ml</th>
          <td>{{ plant.volumeOfWaterInML }}</td>
        </tr>
        <tr>
          <th>Date of last watering</th>
          <td>{{ plant.lastWateringDate|date('d.m.Y') }}</td>
        </tr>
        <tr>
          <th>Description</th>
          <td>{{ plant.description }}</td>
        </tr>
        <tr>
          <th>Fertilizers</th>
          <td>{{ plant.fertilizers|join('') }}</td>
        </tr>
      </tbody>
    </table>
  </div>

  <a href="{{ path('app_plant_index') }}" class="btn btn-primary m-4">back to list</a>

  <a href="{{ path('app_plant_edit', { id: plant.id }) }}" class="btn btn-primary">edit</a>

  {{ include('plant/_delete_form.html.twig') }}
{% endblock %}